export const Products = [
    {
      id: 1,
      title: "Strawberry",
      category: "fruit",
      price: 10,
      url: "img/strawberry.jpg",
    },
    {
      id: 2,
      title: "Banana",
      category: "fruit",
      price: 2,
      url: "img/banana.png",
    },
    {
      id: 3,
      title: "Apple",
      category: "fruit",
      price: 25,
      url: "img/apple.jpeg",
    },
    {
      id: 4,
      title: "Pineapple",
      category: "fruit",
      price: 100,
      url: "img/pineapple.png",
    },
    {
      id: 5,
      title: "Grapes",
      category: "fruit",
      price: 40,
      url: "img/graphes.jpeg",
    },
    {
      id: 6,
      title: "Cherry",
      category: "fruit",
      price: 8,
      url: "img/cherry.png",
    },
    {
      id: 7,
      title: "Red chilly",
      category: "vegetables",
      price: 30,
      url: "img/red-chilly.jpeg",
    },
    {
      id: 8,
      title: "Capcicum",
      category: "vegetables",
      price: 4,
      url: "img/capcicum.jpeg",
    },
    {
      id: 9,
      title: "Onion",
      category: "fruit",
      price: 20,
      url: "img/onion.jpg",
    },
    {
      id: 10,
      title: "Mashroom",
      category: "vegetables",
      price: 12,
      url: "img/mashroom.png",
    },
    {
      id: 11,
      title: "Guava",
      category: "fruit",
      price: 15,
      url: "img/guava.png",
    },
    {
      id: 12,
      title: "Tomato  ",
      category: "vegetables",
      price: 3,
      url: "img/tomato.png",
    },
    {
      id: 13,
      title: "Brinjal",
      category: "vegetables",
      price: 20,
      url: "img/brinjal.jpeg",
    },
    {
      id: 14,
      title: "Broccoli",
      category: "vegetables",
      price: 50,
      url: "img/broccoli.jpeg",
    },
    {
      id: 15,
      title: "Carrot",
      category: "vegetables",
      price: 10,
      url: "img/carrot.jpg",
    },
  ]